import test from 'node:test';import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';import pg from'pg';
import{createCore}from'../apps/api/src/app.mjs';import{deliverCore,processCoreOutbox}from'../apps/api/src/integrations/institutional-outbox.mjs';
import{validateIntake}from'../apps/api/src/modules/commercial-intake.mjs';import{validateKey,commercialPermission}from'../apps/api/src/modules/commercial-keys.mjs';
const payload=(ref=randomUUID(),product='sites')=>({lead:{name:'Pessoa de teste',email:'inbound@example.invalid',whatsapp:'5511999999999',message:'Teste\nSem envio externo'},organization:{organization_type:'person'},commercial:{product_id:product,service_model:'consulting',label:'Diagnóstico de teste'},attribution:{source_ref:ref,source_system:'integration-test'},privacy:{contact_allowed:false,source:'test'}});
test('commercial input rejects forged fields and incomplete contact permission',()=>{
 assert.throws(()=>validateIntake({...payload(),tenant_id:randomUUID()},'sites'));
 const p=payload();p.privacy.contact_allowed=true;assert.throws(()=>validateIntake(p,'sites'));assert.throws(()=>validateIntake(payload(),'skiller'));
 assert.throws(()=>validateKey({product_id:'sites',label:'x',scopes:['admin'],expires_at:new Date(Date.now()+86400000).toISOString()}));
});
test('key administration rejects member and viewer; commercial writes reject viewer',async()=>{
 for(const role of ['member','viewer'])await assert.rejects(commercialPermission({query:async()=>({rows:[{role}]})},{email:'member@example.invalid'},true,true));
 await assert.rejects(commercialPermission({query:async()=>({rows:[{role:'viewer'}]})},{email:'viewer@example.invalid'},true));
});
test('commercial HTTP and queue against isolated PostgreSQL',async t=>{
 const url=process.env.DATABASE_URL_TEST;
 // Esta suíte cria triggers e apaga os próprios dados. Sem uma base dedicada,
 // ela fica explicitamente pendente em vez de tocar a base compartilhada ou
 // transformar a ausência de infraestrutura opcional em regressão do produto.
 if(!url||!/^\/tzolkin_test_commercial_[0-9a-f]{12}$/.test(new URL(url).pathname))return t.skip('DATABASE_URL_TEST dedicada não configurada');
 const pool=new pg.Pool({connectionString:url,max:8});const password='test-only-bootstrap-'+randomUUID();const server=createCore({pool,adminPassword:password});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let cookie,key,leadId;
 const request=async(path,method='GET',body,headers={})=>{const r=await fetch(origin+path,{method,headers:{'content-type':'application/json',origin,cookie:cookie||'',...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json(),headers:r.headers};};
 const intake=(p,k=randomUUID(),token=key.api_key)=>request('/v1/commercial/intake','POST',p,{authorization:'Bearer '+token,'idempotency-key':k,origin:'',cookie:''});
 const issue=async(product='sites',scopes=['commercial:intake','commercial:read'])=>(await request('/api/app-clients','POST',{product_id:product,label:'Integration test',scopes,expires_at:new Date(Date.now()+86400000).toISOString()}));
 try {
 await t.test('anonymous denied and admin CSRF still enforced',async()=>{assert.equal((await request('/api/app-clients?product_id=sites')).status,401);const login=await request('/api/login','POST',{password});cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/app-clients','POST',{}, {origin:''})).status,403);});
 await t.test('issue key returns secret once; list contains scopes but no hash',async()=>{const issued=await issue();assert.equal(issued.status,200,JSON.stringify(issued.body));key=issued.body;const list=await request('/api/app-clients?product_id=sites');assert.equal(list.body.keys.length,1);assert.equal(JSON.stringify(list.body).includes(key.api_key),false);assert.equal(JSON.stringify(list.body).includes('token_hash'),false);});
 await t.test('service intake without Origin persists PF and preserves service model',async()=>{const r=await intake(payload());assert.equal(r.status,200,JSON.stringify(r.body));leadId=r.body.lead_id;assert.equal(r.body.contract_id,null);const d=await request('/api/commercial/leads/'+leadId);assert.equal(d.body.lead.service_model,'consulting');assert.equal(d.body.activities.length,1);assert.equal((await pool.query('select count(*)::int as n from entitlements')).rows[0].n,0);});
 await t.test('parallel identical replay has one lead; different content returns 409',async()=>{const p=payload(),k=randomUUID();const calls=await Promise.all(Array.from({length:6},()=>intake(p,k)));assert.deepEqual(calls.map(x=>x.status),[200,200,200,200,200,200]);assert.equal(new Set(calls.map(x=>x.body.lead_id)).size,1);assert.equal((await intake({...p,lead:{...p.lead,name:'Alterado'}},k)).status,409);const replay=await intake(p);assert.equal(replay.status,200);assert.equal(replay.body.lead_id,calls[0].body.lead_id);});
 await t.test('product isolation and identical idempotency keys across products',async()=>{const second=(await issue('skiller')).body;const k=randomUUID();assert.equal((await intake(payload(),k)).status,200);assert.equal((await intake(payload(randomUUID(),'skiller'),k,second.api_key)).status,200);assert.equal((await intake(payload(),randomUUID(),second.api_key)).status,403);assert.equal((await request('/v1/commercial/leads/'+leadId,'GET',null,{authorization:'Bearer '+second.api_key,cookie:''})).status,404);});
 await t.test('scope, expiry, last use and rotation are enforced',async()=>{assert.equal((await issue('sites',['context:read'])).status,409,'linha de serviço não recebe chave de contexto');const onlyRead=(await issue('skiller',['context:read'])).body;assert.equal((await intake(payload(),randomUUID(),onlyRead.api_key)).status,401);await pool.query("UPDATE app_clients SET expires_at=now()-interval '1 second' WHERE id=$1",[onlyRead.id]);assert.equal((await request('/v1/context?tenant_id='+randomUUID()+'&subject=test','GET',null,{authorization:'Bearer '+onlyRead.api_key,cookie:''})).status,401);const rotated=await request('/api/app-clients/'+key.id+'/rotate','POST',{expires_at:new Date(Date.now()+86400000).toISOString(),overlap_minutes:0});assert.equal(rotated.status,200);assert.equal((await intake(payload())).status,401);key=rotated.body;assert.equal((await intake(payload())).status,200);const list=(await request('/api/app-clients?product_id=sites')).body;assert.ok(list.keys.find(x=>x.id===key.id).last_used_at);assert.ok(list.audit.some(x=>x.action==='rotated'));});
 await t.test('owner, lost reason, timeline and optimistic version',async()=>{const id=(await pool.query("INSERT INTO operator_accounts(email,name,role,status,source) VALUES('commercial-owner@example.invalid','Teste','member','active','manual') RETURNING id")).rows[0].id;assert.equal((await request('/api/commercial/leads/'+leadId,'PUT',{version:1,status:'lost',owner_id:id})).status,400);assert.equal((await request('/api/commercial/leads/'+leadId,'PUT',{version:1,status:'lost',owner_id:id,loss_reason:'Escopo incompatível'})).status,200);assert.equal((await request('/api/commercial/leads/'+leadId,'PUT',{version:1,status:'open'})).status,409);assert.equal((await request('/api/commercial/leads/'+leadId+'/activities','POST',{kind:'call',note:'Contato sintético registrado, sem ligação real.'})).status,200);const d=(await request('/api/commercial/leads/'+leadId)).body;assert.equal(d.lead.owner_id,id);assert.equal(d.activities.length,3);assert.equal((await request('/api/commercial/leads?status=lost')).body.leads.length,1);});
 await t.test('contract requires acceptance and never creates entitlement',async()=>{const created=await request('/api/commercial/contracts','POST',{lead_id:leadId,title:'Contrato de teste',scope:'Entregável sintético',amount_minor:10000,currency:'BRL'});assert.equal(created.status,200,JSON.stringify(created.body));const c=created.body.contract;assert.equal((await request('/api/commercial/contracts/'+c.id+'/status','PUT',{version:1,status:'active'})).status,400);assert.equal((await request('/api/commercial/contracts/'+c.id+'/status','PUT',{version:1,status:'active',acceptance_reference:'Aceite sintético de teste'})).status,200);assert.equal((await pool.query('select count(*)::int as n from entitlements')).rows[0].n,0);});
 await t.test('transaction rollback leaves no partial lead when timeline fails',async()=>{await pool.query("CREATE FUNCTION reject_test_activity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected failure'; END $$; CREATE TRIGGER test_activity_failure BEFORE INSERT ON commercial_activities FOR EACH ROW EXECUTE FUNCTION reject_test_activity()");const before=(await pool.query('SELECT count(*)::int n FROM tenants')).rows[0].n;assert.equal((await intake(payload())).status,500);assert.equal((await pool.query('SELECT count(*)::int n FROM tenants')).rows[0].n,before);await pool.query('DROP TRIGGER test_activity_failure ON commercial_activities; DROP FUNCTION reject_test_activity()');});
 await t.test('Site outbox is atomic, retries after outage, delivers via HTTP and survives lost acknowledgement',async()=>{
 const row=(await pool.query("INSERT INTO institucional.leads(full_name,email,whatsapp,service) VALUES('Teste Site','site@example.invalid','5511988888888','Sites Institucionais') RETURNING id")).rows[0];const out=(await pool.query('SELECT * FROM institucional.core_outbox WHERE lead_id=$1',[row.id])).rows[0];assert.ok(out);
 assert.equal(await processCoreOutbox(pool,async()=>({ok:false,retryable:true,code:'outage'})),'retry');await pool.query("UPDATE institucional.core_outbox SET next_attempt_at=now() WHERE id=$1",[out.id]);
 const send=(p,k)=>deliverCore(p,k,{url:origin,token:key.api_key});assert.equal(await processCoreOutbox(pool,send),'delivered');const delivered=(await pool.query('SELECT * FROM institucional.core_outbox WHERE id=$1',[out.id])).rows[0];assert.ok(delivered.core_lead_id);
 await pool.query("UPDATE institucional.core_outbox SET status='processing',lease_until=now()-interval '1 minute' WHERE id=$1",[out.id]);assert.equal(await processCoreOutbox(pool,send),'delivered');assert.equal((await pool.query('SELECT count(*)::int n FROM commercial_leads WHERE source_ref=$1',[row.id])).rows[0].n,1);
 const tx=await pool.connect();await tx.query('BEGIN');await tx.query("INSERT INTO institucional.leads(full_name,email,whatsapp,service) VALUES('Rolled back','rollback@example.invalid','5511988888888','Sites Institucionais')");await tx.query('ROLLBACK');tx.release();assert.equal((await pool.query('SELECT count(*)::int n FROM institucional.core_outbox')).rows[0].n,1);
 });
 await t.test('revoked key denied immediately and recorded',async()=>{assert.equal((await request('/api/app-clients/'+key.id,'DELETE')).status,200);assert.equal((await intake(payload())).status,401);assert.ok((await request('/api/app-clients?product_id=sites')).body.audit.some(x=>x.action==='revoked'));});
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));await pool.end();}
});
